- README.md
https://play.google.com/store/apps/details?id=com.mikpenz.iconics.sample
> Edited the play store link

- .gitignore
- app/build.gradle
- app/src/main/java/com/mikepenz/iconics/sample/IconsFragment.java
- app/src/main/java/com/mikepenz/iconics/sample/MainActivity.java
- app/src/main/java/com/mikepenz/iconics/sample/adapter/IconAdapter.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/icons_fragment.xml
- app/src/main/res/values/colors.xml
Just, use NavDrawer!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mikepenz/android-iconics/22)
> Display icons from Navigation Drawer

- app/src/main/java/com/mikepenz/iconics/sample/PlaygroundActivity.java
- app/src/main/res/layout/activity_playground.xml
- app/src/main/res/layout/row_icon_array.xml
- library/src/main/java/com/mikepenz/iconics/Iconics.java
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mikepenz/android-iconics/39)
> Multiple IIcons creation.

- README.md
I've added Proguard rules to make library work when minification `minifyEnabled true` is enabled
> Added Proguard rules

- README.md
- community-material-typeface-library/build.gradle
- community-material-typeface-library/consumer-proguard-rules.pro
- fontawesome-typeface-library/build.gradle
- fontawesome-typeface-library/consumer-proguard-rules.pro
- google-material-typeface-library/build.gradle
- google-material-typeface-library/consumer-proguard-rules.pro
- meteocons-typeface-library/build.gradle
- meteocons-typeface-library/consumer-proguard-rules.pro
- octicons-typeface-library/build.gradle
- octicons-typeface-library/consumer-proguard-rules.pro
What do you think of this, @mikepenz ?
> Include consumer ProGuard rules in font AARs

- README.md
A great service for assembling custom icon fonts.
> adding Fontastic

- library-core/src/main/java/com/mikepenz/iconics/Iconics.java
Add iconExists method to check icon availability.
> Add iconExists method to check icon availability.

- library-core/src/main/java/com/mikepenz/iconics/utils/Utils.java
- library-core/src/main/java/com/mikepenz/iconics/view/IconicsTextView.java
- library-core/src/main/res/values/attrs.xml
- library-core/src/main/res/values/strings.xml
https://github.com/mikepenz/Android-Iconics/issues/291
> resolved issue #291

- library-core/src/main/java/com/mikepenz/iconics/view/IconicsTextView.java
I'am forgot do initial invoke setIcons() method
> fixed missing call setIcons() method

- build.gradle
- iconics-view-library/src/main/java/com/mikepenz/iconics/internal/IconicsViewsAttrsReader.java
- iconics-view-library/src/main/java/com/mikepenz/iconics/view/IconicsButton.java
- iconics-view-library/src/main/java/com/mikepenz/iconics/view/IconicsImageButton.java
- iconics-view-library/src/main/java/com/mikepenz/iconics/view/IconicsImageView.java
- iconics-view-library/src/main/java/com/mikepenz/iconics/view/IconicsTextView.java
- Deprecated proxy-methods in IconicsImageView
- Updated years in copyrights
- Android support libraries bumped to v26.0.1
> Deprecations for proxy methods

- library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.java
- Some of methods doesn't call `invalidateSelf()` and finally does nothing in the end of chain
> Fix invalidateSelf()

- library-core/src/main/java/com/mikepenz/iconics/Iconics.java
- library-core/src/main/java/com/mikepenz/iconics/IconicsArrayBuilder.java
- library-core/src/main/java/com/mikepenz/iconics/IconicsBrush.java
- library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.java
- library-core/src/main/java/com/mikepenz/iconics/animation/BlinkAlphaProcessor.java
- library-core/src/main/java/com/mikepenz/iconics/animation/BlinkScaleProcessor.java
- library-core/src/main/java/com/mikepenz/iconics/animation/IconicsAnimatedDrawable.java
- library-core/src/main/java/com/mikepenz/iconics/animation/IconicsAnimationProcessor.java
- library-core/src/main/java/com/mikepenz/iconics/animation/SpinProcessor.java
- library-core/src/main/java/com/mikepenz/iconics/context/IconicsAttrsApplier.java
- library-core/src/main/java/com/mikepenz/iconics/context/IconicsAttrsExtractor.java
- Fixed code formatting
- Code cleanup
> [Refactoring] Fixed code formatting

- library-core/src/main/java/com/mikepenz/iconics/utils/IconicsMenuInflaterUtil.java
- Added utility method for set icons w/o inflating menu
(includes changes from #423)
> [Feature] Utility method for set icons w/o inflating menu

- app/build.gradle
- app/src/main/res/layout/activity_playground.xml
- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- iconics-view-library/build.gradle
- library-core/build.gradle
- library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.java
- fix for #426
- bump deps versions
- change gradle version for AS 3.3
> Fix for #426

- library-core/src/main/java/com/mikepenz/iconics/IconicsBrush.java
- fixed unchangeable wrong alpha value (#442)
> Fix for #442

- library-core/src/main/java/com/mikepenz/iconics/context/IconicsLayoutInflater.kt
- library-core/src/main/java/com/mikepenz/iconics/context/IconicsLayoutInflater2.kt
- library-core/src/main/java/com/mikepenz/iconics/context/InternalLayoutInflater.kt
> wrong override for parameter "parent"

- library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.java
> Broken stateable colors

- .travis.yml
- DEV/default-detekt-config.yml
- app/build.gradle
- app/src/main/java/com/mikepenz/iconics/sample/CustomApplication.kt
- app/src/main/java/com/mikepenz/iconics/sample/IconsFragment.kt
- app/src/main/java/com/mikepenz/iconics/sample/MainActivity.kt
- app/src/main/java/com/mikepenz/iconics/sample/PlaygroundActivity.kt
- app/src/main/java/com/mikepenz/iconics/sample/item/IconItem.kt
- build.gradle
- detekt.gradle
- iconics-view-library/build.gradle
- iconics-view-library/src/main/java/com/mikepenz/iconics/view/IconicsTextView.kt
- library-core/build.gradle
- library-core/src/main/java/com/mikepenz/iconics/IconicsColor.kt
- library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.kt
- library-core/src/main/java/com/mikepenz/iconics/IconicsSize.kt
- library-core/src/main/java/com/mikepenz/iconics/context/IconicsAttrsExtractor.kt
- library-core/src/main/java/com/mikepenz/iconics/context/InternalLayoutInflater.kt
- library-core/src/main/java/com/mikepenz/iconics/utils/IconicsConverters.kt
* add and enable detekt static code analysis
> Add detekt

- library-core/src/main/java/com/mikepenz/iconics/context/IconicsAttrsApplier.kt
Fixes #477 
Sorry about this 🤦‍♂
> Pass the value of attribute "ico_automirror" to the IconicsDrawable

- app/build.gradle
- build.gradle
- update dependencies to their latest stable releases
- compileSdk 30
- buildTools 30.0.2
- target 30
- kotlin 1.4.10
- material 1.2.1
- appcompat 1.2.0
- constraintLayout 2.0.2
- core-ktx 1.3.2
- aboutLibs 8.4.2
- materialDrawer 8.1.6
- fastAdapter 5.2.4
> [...] Dependency updates to latest stable

- .github/config/configuration.json
- .github/workflows/ci.yml
- README.md
- introduce automatic changelog generation for releases
- ignore pre-releases for full releases
- custom config with other section
> Automatic changelog generation for releases

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- gradle 6.7.1
- kotlin 1.4.20
- constraintLayout 2.0.4
- startup 1.0.0
- detekt 1.14.2
- aboutLibs 8.6.0
- materialDrawer 8.1.8
- fastAdapter 5.3.1
> Dependency updates 2020.11.23

- app/build.gradle
- app/src/main/java/com/mikepenz/iconics/sample/IconsFragment.kt
- app/src/main/java/com/mikepenz/iconics/sample/MainActivity.kt
- remove kotlin synthetics and replace view viewbinding
> Remove kotlin  synthetic

- .github/workflows/ci.yml
- release.sh
> dev -> main

- .github/workflows/ci.yml
- app/build.gradle
- build.gradle
- gradle.properties
- library-compose/build.gradle
- library-compose/src/main/java/com/mikepenz/iconics/compose/Image.kt
- update to kotlin 1.4.20
- update to fastAdapter 5.3.2
- update to compose 1.0.0-alpha08
- use new gradle tooling 7.0.0-alpha02
> Update to kotlin 1.4.20, compose 1.0.0-a08

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- update gradle to 6.8-rc-4
- update kotlin to 1.4.21
- update gradle build tools to 7.0.0-alpha03
- update compose to 1.0.0-alpha09
> Update Gradle | Kotlin 1.4.21 | Compose 1.0.0-alpha09

- build.gradle
- update aboutLibraries 6.8.3
- update materialDrawer 8.3.1
- update detekt 1.15.0
> Update sample dependencies

- .github/workflows/ci.yml
- build.gradle
- gradle-release.gradle
- gradle/wrapper/gradle-wrapper.properties
- release.sh
- update to gradle 6.8.1
- remove bintray plugin
- adjust to only publish to maven central
- update (prepare) CI pipeline for gradle publish
- update script for maven publish
> Discontinue publication to bintray

- .github/workflows/ci.yml
- adjust ci build to automatically publish tags to sonatype
> Automatically stage release via tags to sonatype

- .github/workflows/ci.yml
- gradle.properties
- iconics-core/build.gradle
- slightly cleanup 
- rename task in pipeline
- use spdx identifier as license name
> Use SPDX pom license identifier

- build.gradle
- community-material-typeface-library/build.gradle
- devicon-typeface-library/build.gradle
- entypo-typeface-library/build.gradle
- fontawesome-typeface-library/build.gradle
- foundation-icons-typeface-library/build.gradle
- google-material-typeface/google-material-typeface-library/build.gradle
- google-material-typeface/google-material-typeface-outlined-library/build.gradle
- google-material-typeface/google-material-typeface-rounded-library/build.gradle
- google-material-typeface/google-material-typeface-sharp-library/build.gradle
- gradle-release.gradle
- iconics-core/build.gradle
- iconics-typeface-api/build.gradle
- iconics-views/build.gradle
- ionicons-typeface-library/build.gradle
- material-design-dx-typeface-library/build.gradle
- material-design-iconic-typeface-library/build.gradle
- meteocons-typeface-library/build.gradle
- octicons-typeface-library/build.gradle
- phosphor-typeface-library/build.gradle
- pixeden-7-stroke-typeface-library/build.gradle
- typeicons-typeface-library/build.gradle
- weather-icons-typeface-library/build.gradle
- update project to properly provide transitive dependencies
- update gradle-release.gradle script to ensure dependencies as compile
- cleanup duplicated dependency specifications
- cleanup sample app gradle some more
> Update project to properly have transitive dependencies as compile

- build.gradle
- update to compose 1.0.0-beta01
- update to android build tools alpha08
> Compose 1.0.0-beta01

- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- update to gradle 6.8.3
- junit 4.13.2
> Gradle 6.8.3

- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- update dependencies to latest stable iteration
- kotlin 1.5.10
- recyclerView 1.2.0
- core 1.5.0
- appcompat 1.3.0
- compose 1.0.0-beta07
> Upgrade dependencies

- build.gradle
- update dependencies to their latest stable version
- material 1.4.0
- appcompat 1.3.1
- aboutLibraries 8.9.1
- materialDrawer 8.4.1
- compose 1.0.0
> Update dependencies | Compose 1.0.0

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- upgrade dependencies to latest stable version
- compose 1.0.2
- kotlin 1.5.21
- build tools 31.0.0
- compileSdk 31
- startup 1.1.0
- detekt 1.18.1
- materialDrawer 8.4.3
- fastAdapter 5.5.1
> Upgrade dependencies to latest stable version

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- iconics-compose/src/main/java/com/mikepenz/iconics/compose/ExperimentalIconics.kt
- iconics-compose/src/main/java/com/mikepenz/iconics/compose/IconicsPainter.kt
- iconics-compose/src/main/java/com/mikepenz/iconics/compose/Image.kt
- the compose extension is now stable, remove experimental api
> Compose API extension, now stable

- README.md
- iconics-core/src/main/java/com/mikepenz/iconics/Iconics.kt
- add README note on `jetpack startup` requirement
- FIX https://github.com/mikepenz/Android-Iconics/issues/609
> Add info regarding the use of jetpack startup library

- README.md
- add note on `@aar` spec when using version catalog
> Update README with note on `@aar` for typefaces
