library/src/main/java/com/mikepenz/iconics/view/IconicsImageView.java

Change scaling type to use CENTER_INSIDE.
(Android M seems to have changed the behavior of MATRIX scaling type.)

Fix the issue #50 (Padding is not working properly on Android M)

---

app/src/main/res/layout/activity_playground.xml
library-core/src/main/java/com/mikepenz/iconics/view/IconicsImageView.java

Hi. I noticed these two issues of the `IconicsImageView` and this PR fixes them.
1. The `iiv_padding` property is not applied properly
2. Icon is scaled to fit the view size on Android 6.0
I have confirmed this works properly on Android 2.3.7, 4.3, 4.4.3, 5.0.2 and 6.0. Thanks!
| 2.3.7 | 4.3 | 4.4.3 | 5.0.2 | 6.0 |
|-----|-----|-----|-----|-----|
| <img src="https://cloud.githubusercontent.com/assets/2552365/10475908/a3c6cb24-7283-11e5-8c71-ed173f1075d8.png" width="150" /> | <img src="https://cloud.githubusercontent.com/assets/2552365/10475838/ed68b3ba-7282-11e5-8e37-6149194d7dba.png" width="150" /> | <img src="https://cloud.githubusercontent.com/assets/2552365/10475819/c12d9388-7282-11e5-98e0-444d4a9b9db1.png" width="150" /> | <img …

Fix IconicsImageView icon size issue

---

library-core/src/main/java/com/mikepenz/iconics/context/InternalLayoutInflater.java

This issue (as far as I can tell) only appears on the attachBaseContext() way of setting up Iconics. When a WebView is included in a layout, the activity crashes with a ClassNotFoundException because WebView is (unlike most - maybe all - other Android widgets) in the android.webkit namespace. Adding this namespace to the class prefix list fixes it. You can see [Calligraphy does the same](https://github.com/chrisjenx/Calligraphy/blob/master/calligraphy/src/main/java/uk/co/chrisjenx/calligraphy/CalligraphyLayoutInflater.java#L24). I hope this helps.
Thanks for a great library!

Fix issue with WebViews when injecting into Context

---

library-core/src/main/java/com/mikepenz/iconics/typeface/GenericFont.java

First of all, thanks for this great library. XD
So.. I added mappingPrefix validation in GenericFont constructor, because I overlooked the rule that `Create a new GenericFont by defining a 3 char long fontId...`  :fearful:

Add mappingPrefix validation

---

library-core/src/main/java/com/mikepenz/iconics/Iconics.java

As proposed in issue #224, add a simple length check to the mapping prefix, to prevent confusing error messages if an incorrect length is used

Add a simple sanity check to registered fonts

---

library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.java
library-core/src/main/java/com/mikepenz/iconics/context/IconicsFactory.java

This adds support for `IconicsDrawable.color(ColorStateList colors)` to set multiple state dependent colors. It should be fully backwards compatible since every `int`-color can be converted to a `ColorStateList` and the [TypedArray.getColorStateList](https://developer.android.com/reference/android/content/res/TypedArray.html#getColorStateList(int)) used in `IconicsFactory` works on both, simple integer colors and state lists.
I had to introduce a update method that is very similar to how `TextView` does its updating.
Any feedback? Is this a welcomed addition?

Add support for color(ColorStateList) in IconicsDrawable

---

library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.java
library-core/src/main/java/com/mikepenz/iconics/utils/IconicsMenuInflatorUtil.java

The utiltiy class can be used like this:
@Override
public boolean onCreateOptionsMenu(Menu menu)
{
MenuInflater inflater = getMenuInflater();
IconicsMenuInflatorUtil.inflate(inflater, this, R.menu.menu_main, menu);
return true;
}
With a menu like this:
<?xml version="1.0" encoding="utf-8"?>
<menu
xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:app="http://schemas.android.com/apk/res-auto">
<item
android:id="@+id/menu_help"
app:showAsAction="always"
android:title="@string/menu_help"
app:iiv_color="@color/md_white_1000"
app:iiv_icon="gmd-help-outline"
app:iiv_size="24dp" />
</menu>
Currently I use the style of the `IconicsImageView` in the menus, because I need some styleable definition for the parser, we could define a own one for the menu, but it's not really necessary...

IconicsMenuInflatorUtil added

---

README.md

I was wondering why the TextView example from the readme was not working, until I figured out that the icon `gmd-chart` does not exist. I updated it to `gmd-bubble-chart`.

Fix TextView example in readme

---

library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.java

It happens when you open Android studio's layout preview where some of your views try to use IconicsDrawable. Because layout preview doesn't support Paint.getTextPath(), path itself will be empty, and when you try to close it, it throws the exception.
Simple fix is to check if path is not empty before trying to close it.

Fix exception when closing empty path

---

library-core/src/main/java/com/mikepenz/iconics/utils/IconicsMenuInflaterUtil.java

This fixes non literal ids in menus leading to a crash.
Happens in app bundles and is also reproducable in the sample app when building an app bundle and navigating to the playground.
Fixes #391. Thanks @MFlisar for the fix, this is basically what you commented!

Fix the IconicsMenuInflaterUtil to be able to handle non literal ids

---

README.md

As talked in issue #287, a quick PR to add a reference to the Android module generator

Add reference to IconicsFontGenerator in Readme

---

build.gradle
library-core/src/main/java/com/mikepenz/iconics/animation/IconicsAnimationProcessor.java

- Updated build tools version
- Fixed crash on 4.1 when platform (less than 4.4) cant find `android.animation.Animator.AnimatorPauseListener` (added since 4.4) #436

Fixed crash on 4.1 (#436)

---

app/build.gradle
app/src/main/java/com/mikepenz/iconics/sample/IconsFragment.kt
app/src/main/java/com/mikepenz/iconics/sample/MainActivity.kt
app/src/main/java/com/mikepenz/iconics/sample/PlaygroundActivity.kt
app/src/main/java/com/mikepenz/iconics/sample/item/IconItem.kt
build.gradle
iconics-view-library/build.gradle
library-core/build.gradle
library-core/src/main/java/com/mikepenz/iconics/IconicsColor.kt
library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.kt
library-core/src/main/java/com/mikepenz/iconics/IconicsSize.kt
library-core/src/main/java/com/mikepenz/iconics/context/IconicsAttrsExtractor.kt
library-core/src/main/java/com/mikepenz/iconics/utils/IconicsConverters.kt

* use sealed class for `IconicsColor` as suggested by: #456
* ContextCompat.getColor retrieves the default color already
* introduce more extension functions to converters …
* deprecate old converters, introduce proper replace rule
* deprecate old extension functions in IconicsDrawable class
* refactor code to make use of new proper extension funcions
cc @AllanWang

Sealed classes for IconicsColor and IconicsSize

---

app/src/main/AndroidManifest.xml
app/src/main/res/layout/activity_playground.xml
iconics-view-library/src/main/java/com/mikepenz/iconics/internal/IconicsViewsAttrsApplier.kt
iconics-view-library/src/main/res/values/attrs.xml
library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.kt
library-core/src/main/java/com/mikepenz/iconics/context/IconicsAttrsExtractor.kt
library-core/src/main/res/values/attrs.xml

This PR adds attributes to the core library and the different views to allow mirroring the drawable when the drawable layout direction is RTL.
This depends on layoutDirection field of Drawable class, so it's available on API 17 and higher only.

Add support of auto mirroring on RTL languages

---

README.md

I'm wondering if `"...${latestFastAdapterRelease}"` was a typo or the two libraries versions were matching in the past.

Improve Gradle section of the README

---

README.md
app/src/main/res/layout/activity_playground.xml
app/src/main/res/values-v21/themes.xml
app/src/main/res/values/themes.xml
build.gradle
community-material-typeface-library/build.gradle
devicon-typeface-library/build.gradle
entypo-typeface-library/build.gradle
fontawesome-typeface-library/build.gradle
foundation-icons-typeface-library/build.gradle
google-material-typeface-library/build.gradle
gradle-release.gradle
ionicons-typeface-library/build.gradle
material-design-dx-typeface-library/build.gradle
material-design-iconic-typeface-library/build.gradle
meteocons-typeface-library/build.gradle
octicons-typeface-library/build.gradle
pixeden-7-stroke-typeface-library/build.gradle
typeicons-typeface-library/build.gradle
weather-icons-typeface-library/build.gradle

- [release] v5.1.0
- update all font addons to use jetpack app startup
```
implementation 'com.mikepenz:google-material-typeface:3.0.1.5.original-kotlin@aar'
implementation 'com.mikepenz:community-material-typeface:5.3.45.2-kotlin@aar'
implementation 'com.mikepenz:devicon-typeface:2.0.0.6-kotlin@aar'
implementation 'com.mikepenz:entypo-typeface:1.0.0.6-kotlin@aar'
implementation 'com.mikepenz:fontawesome-typeface:5.9.0.1-kotlin@aar'
implementation 'com.mikepenz:foundation-icons-typeface:3.0.0.6-kotlin@aar'
implementation 'com.mikepenz:ionicons-typeface:2.0.1.6-kotlin@aar'
implementation 'com.mikepenz:material-design-icons-dx-typeface:5.0.1.1-kotlin@aar'
implementation 'com.mikepenz:material-design-iconic-typeface:2.2.0.7-kotlin@aar'
implementation …
```

Release 5.1.0 -> dev

---

iconics-view-library/src/main/java/com/mikepenz/iconics/view/IconicsTextView.kt

- adjust `setText` to allow null input
- FIX https://github.com/mikepenz/Android-Iconics/issues/529

Allow null for `setText` in IconicsTextView

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
library-core/build.gradle
library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.kt
library-core/src/main/java/com/mikepenz/iconics/WrappedDrawable.java
library-typeface-api/build.gradle

- fix compile issue by wrapping the drawable class in java 
- `setState` can be null but is wrongfully annotated as non null in newer android versions

Fix `setState` nullable annotation compile issue

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
iconics-compose/src/main/java/com/mikepenz/iconics/compose/Image.kt

- update to gradle 6.8.2
- update dependencies to latest stable version
- update to compose-alpha11 and make image compatible again

Dependency updates | Compose alpha11 compatiblity update

---

build.gradle

- update to Kotlin 1.4.30
- update to aboutLibraries 8.8.2
- update to MaterialDrawer 8.3.3
- update to compose 1.0.0-alpha12
- update gradle build tools alpha07

Dependency updates | Kotlin 1.4.30 | Compose 1.0.0-alpha12

---

README.md

- add compatibility note on appcompat:1.4.x
- RELATED https://github.com/mikepenz/Android-Iconics/issues/592

Highlight appcompat:1.4.x emoji support incompatiblity

---

iconics-core/src/main/java/com/mikepenz/iconics/utils/IconicsDrawableExtensions.kt

- add log message in case of the requested font not being registered
- FIX https://github.com/mikepenz/Android-Iconics/issues/609#issuecomment-962400829

Log on missing font

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

- update materialdrawer and aboutlibraries
- material 1.5.0-beta01
- gradle 7.3

Dependency updates 2021.11.12
